const functions = require("firebase-functions");
const admin = require("firebase-admin");
const nodemailer = require("nodemailer");

admin.initializeApp();

const gmailEmail = process.env.EMAIL_USER;
const gmailPass = process.env.EMAIL_PASS;

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: gmailEmail,
    pass: gmailPass,
  },
});

exports.sendFeedbackEmail = functions.firestore
  .document("feedback/{docId}")
  .onCreate(async (snap, context) => {
    const data = snap.data();
    const { name, email, message, createdAt } = data;

    const mailOptions = {
      from: `"MindCraft Feedback" <${gmailEmail}>`,
      to: "support.mindcraft@gmail.com",
      subject: `📬 New Feedback from ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; background: #f9fafb; border-radius: 12px;">
          <h2 style="color: #2563eb; margin-bottom: 4px;">New Feedback Received</h2>
          <p style="color: #6b7280; font-size: 13px; margin-top: 0;">MindCraft Website — Feedback Form</p>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;" />
          <table style="width: 100%; border-collapse: collapse;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; width: 120px;">Name</td>
              <td style="padding: 8px 0; color: #111827;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Email</td>
              <td style="padding: 8px 0; color: #2563eb;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151; vertical-align: top;">Message</td>
              <td style="padding: 8px 0; color: #111827; white-space: pre-wrap;">${message}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #374151;">Submitted At</td>
              <td style="padding: 8px 0; color: #6b7280;">${createdAt || new Date().toISOString()}</td>
            </tr>
          </table>
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;" />
          <p style="color: #9ca3af; font-size: 12px; text-align: center;">This email was automatically generated by MindCraft.</p>
        </div>
      `,
    };

    try {
      await transporter.sendMail(mailOptions);
      console.log(`Feedback email sent successfully for doc: ${context.params.docId}`);
    } catch (error) {
      console.error("Error sending feedback email:", error);
    }
  });
